### ISSUE TITLE
Support M1 chips

### ISSUE THREAD

**Issue by pmorelli92** [natenho/Mockaco#104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure a similar issue has not already been created

### Description

Enable support for ARM/64 so it does not have to run through emulation.

### Proposed solution

Use the docker multi architecture `buildx` to generate images for different platforms:

https://docs.docker.com/desktop/multi-arch/

**Comment by natenho** [comment]
Hi @pmorelli92 would you be interested to send a pull request implementing that? :)
