### ISSUE TITLE
Scripting Broken: Message: Incoming request didn't match any mock

### ISSUE THREAD

**Issue by Im5tu** [natenho/Mockaco#105]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing bugs to ensure a similar bug has not already been created

### Description

If you add include any templated response, you receive "Message: Incoming request didn't match any mock" in the response. 

### Steps to reproduce

Copy the hello json file and mount with test containers:

```csharp
public class MockacoContainer : IAsyncLifetime
{
    private static readonly HashSet<int> RunningPorts = new HashSet<int>();
    private readonly TestcontainersContainer _container;

    public int ContainerPort { get; }
    public string ContainerUri => $"http://localhost:{ContainerPort}";

    protected MockacoContainer(string scenario)
    {
        lock(RunningPorts)
        {
            do
            {
                ContainerPort = Random.Shared.Next(4000, 5000);
            }
            while (RunningPorts.Contains(ContainerPort));
            RunningPorts.Add(ContainerPort);
        }

        _container = new TestcontainersBuilder<TestcontainersContainer>()
            .WithImage("natenho/mockaco")
            .WithCleanUp(true)
            .WithPortBinding(ContainerPort, 5000)
            .WithWaitStrategy(Wait.ForUnixContainer()
                .UntilPortIsAvailable(5000)
            )
            .WithBindMount(ToAbsolute($"./mockaco/{scenario}"), "/app/Mocks", AccessMode.ReadWrite)
            .Build();
    }

    public async Task InitializeAsync()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));
        await _container.StartAsync(cts.Token);
    }

    public async Task DisposeAsync()
    {
        await Task.Delay(TimeSpan.FromMinutes(1));
        await _container.DisposeAsync();
    }

    private static string ToAbsolute(string path) => Path.GetFullPath(path);
}
```

### Expected behavior

Response returned as per example

**Comment by natenho** [comment]
Hi @Im5tu , could you help me understand your scenario? I'm not familiar with TestcontainersContainer, but I was able to test the regular hello demo using Docker like this:

Given [hello.json](https://raw.githubusercontent.com/natenho/Mockaco/master/src/Mockaco/Mocks/hello.json) in a given /Mocks directory in my host machine:

```
docker run -it --rm -p 5000:5000 -v $(pwd)/Mocks:/app/Mocks natenho/mockaco
```
```
$ curl -i http://localhost:5000/hello/test
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 26 Sep 2022 05:39:16 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "id": "c4919955-b46f-1484-5552-f55b2ceab3da",
  "message": "Hello test!",
  "createdAt": "2022-09-26T05:39:16.2262442+00:00"
}
```

Can you access the logs to check if Mockaco is properly loading your mock template like the screenshot below?

![image](https://user-images.githubusercontent.com/4236481/192202057-833eb901-6307-4dff-880d-37431d7004ad.png)

**Comment by Im5tu** [comment]
@natenho - I think I've found the issue. Basically when the container starts the API is immediately available but the files haven't been mapped straight away. The immediate fix for me is to add a delay before allowing the tests to run, eg:

```csharp
public async Task InitializeAsync()
{
    using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));
    await _container.StartAsync(cts.Token);
    await Task.Delay(TimeSpan.FromSeconds(10));
}
```

It's strange that this only happens when there is a script section, assumingly because there is the templating taking a bit of time?

Is there an endpoint that I can call to check to see if everything is initialized at all? I didn't see one on a quick look around the repository. If there isn't, please could we add one or do the parsing before the API becomes available so we don't hit this timing issue?

Now that I've figured out the problem, I can continue the video I was going to do on this for my YT channel :)

**Comment by natenho** [comment]
@Im5tu, glad to read that you find a way to proceed and yes, you are probably right, the scripting engine generates a little overhead to the loading time and can lead to some race condition if you're expecting mocks to be ready right after Mockaco is listening. Actually we don't have any readiness endpoint, it surely can be useful for scenarios like yours.

I'd be honored to be mentioned in your channel! I can be found as @natenho everywhere, although I'm not too much active on social media as you will notice ;-) Thank you

**Comment by natenho** [comment]
- We can leverage [Health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?
view=aspnetcore-7.0) to add a readiness endpoint.
- We could also provide an option to start listening only after all mock templates are loaded.

**Comment by Im5tu** [comment]
Personally I think that the readiness endpoint would be best and more consistent with what others would expect (:

**Comment by natenho** [comment]
@Im5tu the feature has been added to the last release ;) Check-out the docs at https://natenho.github.io/Mockaco/docs/health-checks/
