### ISSUE TITLE
Include request headers in verification endpoint

### ISSUE THREAD

**Issue by leandrodasilvaalves** [natenho/Mockaco#117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure a similar issue has not already been created

### Description

Hey guys! Everything is OK?
Recently I used Mockaco at work to simulate an integration with a third-party web api and the verification endpoint helped me a lot to understand that my work was working fine. However, I missed being able to see if the headers are being sent correctly in the request.

### Proposed solution

It would be really cool if in a request similar to the example below where we send some headers, we had the possibility to visualize them in the verification endpoint.

1. Request endpoint Mock
```
curl --location --request POST 'http://localhost:5000/hello/message-1' \
--header 'x-header-1: h001' \
--header 'x-header-2: h002' \
--header 'x-user-id: concact@email.com' \
--header 'x-internal: true' \
--header 'x-e2e: ea692ce1-72b3-4e27-85b8-ff595db2d65f' \
--header 'Authorization: Bearer a5e5b3b7-6c1f-4c14-ab70-e041d9200469' \
--header 'Content-Type: application/json' \
--data-raw '{
    "firstName": "Rachelle",
    "lastName": "Lehner",
    "phones":[
        "638-228-6791",
        "672-842-5750",
        "203-854-0143"
    ],
    "emails":[
        "Ericka.Harber62@gmail.com",
        "Lionel.Gottlieb51@gmail.com",
        "Ima_Hansen50@yahoo.com"
    ]
}'
```
2. Response endpoint verification: `http://localhost:5000/_mockaco/verification?route=/hello/message-1`

```

{
    "route": "/hello/message-1",
    "timestamp": "17:44",
    "headers": [
        {
            "key": "Authorization",
            "value": "Bearer b664381b-b883-4647-b106-b4988c4363f5"
        },
        {
            "key": "x-header-1",
            "value": "h001"
        },
        {
            "key": "x-header-2",
            "value": "h002"
        },
        {
            "key": "x-user-id",
            "value": "leandro@email.com"
        },
        {
            "key": "x-internal",
            "value": "true"
        },
        {
            "key": "x-e2e",
            "value": "65a657f0-3d6c-4ed6-ac0f-c1bd0b29cf91"
        }
    ],
    "body": "{\n    \"firstName\": \"Charles\",\n    \"lastName\": \"Zulauf\",\n    \"phones\":[\n        \"969-204-9304\",\n        \"814-940-3002\",\n        \"871-276-7693\"\n    ],\n    \"emails\":[\n        \"Gaylord_Corkery@yahoo.com\",\n        \"Leonel16@yahoo.com\",\n        \"Brain11@yahoo.com\"\n    ]\n}"
}
```

### Alternatives

I also thought about the possibility of hiding some headers already known, as it happens in postman. For example, in postman, headers such as Host, User-Agent, Postman-Tokent, among others, are not displayed. It would be nice if we had the option to not display these headers and only return what is relevant to the mock.

**Comment by natenho** [comment]
Hi @leandrodasilvaalves good to know that Mockaco helped!
Your suggestion seems to be a nice addition. Are you interested in taking on the task of developing this feature?

**Comment by leandrodasilvaalves** [comment]
Hi @natenho!
Sure! I'd really appreciate implement this feature. Sounds good to me.

**Comment by leandrodasilvaalves** [comment]
Hi @natenho 
I opened a pull request two weeks ago. Did you see? https://github.com/natenho/Mockaco/pulls

I have no experience with open source streaming. So if you need to change anything, let me know.

Grateful

**Comment by natenho** [comment]
Hey @leandrodasilvaalves, thank you for your PR. I'll check it as soon as possible.
