### ISSUE TITLE
Fake.Person.FullName returning back same name on each item in the array

### ISSUE THREAD

**Issue by p0onage** [natenho/Mockaco#119]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing bugs to ensure a similar bug has not already been created

### Description

I'm trying to mock out a different name for each item in the array. When I call the Fake.Person.FullName attribute I get a single static name back across all items in the array. When I call this as a function, Fake.Person.FullName() no results are returned 

### Steps to reproduce

{
    "request": {
      "method": "GET",
      "route": "/name"
    },
    "response": {
      "status": "OK",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "content-type": "*"
      },
      "body": {
          "count": 19,
          "data": [
            {
              "id": 14075,
              "name": "<#= Fake.Person.FullName #>",
            }]
      }
}

### Expected behavior

Return back a random name for each item in the array

**Comment by natenho** [comment]
Hi @p0onage, try this:

```
{
    "request": {
        "method": "GET",
        "route": "/name"
    },
    "response": {
        "status": "OK",
        "headers": {
            "Access-Control-Allow-Origin": "",
            "content-type": ""
        },
        "body": {
            "count": 19,
            "data": [
                {
                    "id": 14075,
                    "name": "<#= new Faker().Person.FullName #>"
                },
                {
                    "id": 14075,
                    "name": "<#= new Faker().Person.FullName #>"
                }
            ]
        }
    }
}
```

The Faker object is a convenience, Mockaco just creates an instace of Faker and Bogus creates a single Person instance. But you can create your own Faker object using the script. :)

**Comment by p0onage** [comment]
Thanks so much @natenho that works!
