### ISSUE TITLE
Prioritize templates containing conditions over those with empty condition

### ISSUE THREAD

**Issue by marcothz** [natenho/Mockaco#24]
Although template files are usually loaded in alphabetical order, currently there is no guaranteed order.
Besides that, the order the templates are loaded is the same they are evaluated.
Because of that, if there are multiple templates targeting the same HTTP method and path and the first loaded is the one with empty condition, the others will never be reached.

**Comment by natenho** [comment]
The master branch is doing that way. 

src/Mockaco/Processors/TemplateProcessor.cs

The refactor branch is not doing that though. =(
I thought that giving the ordering control

**Comment by marcothz** [comment]
Just created a pull request to workaround that on branch "refactor". Please review.

**Comment by natenho** [comment]
Refer to #7

**Comment by natenho** [comment]
#7
