### ISSUE TITLE
URLs that contains non-ASCII characters are failing

### ISSUE THREAD

**Issue by marcothz** [natenho/Mockaco#40]
**To Reproduce**
Just call GET /hello/olá

**Expected behavior**
Do not fail. 😉

**Comment by natenho** [comment]
Hello, thank you for your feedback!

I'm afraid that is not a Mockaco issue. It's actually a Kestrel's team decision to reject non-ASCII characters in HTTP headers. Please refer to https://github.com/aspnet/AspNetCore/issues/5865 for further details.

It's also good to mention that reproducinng the issue may depend on the client/operating system that you are using to perform the request:

- **Postman** may send the actual  ISO 8859-1 (Latin-1) character 0xE1 "á" `GET /hello/ol\xE1` and Kestrel will reject it with a Bad Request (HTTP 400) earlier in ASP.Net Core pipeline, so Mockaco will not have a chance to deal with it.
- **curl** may send the actual UTF-8 characters `GET /hello/ol\xC3\xA1` and Kestrel will reject it with a Bad Request (HTTP 400) as well.
- Browsers such as **Google Chrome** and **Microsoft Edge** in the other hand transform the input and send as `GET /hello/ol%C3%A1` (UTF-8 URL-encoded) so Kestrel will seamlessly accept it, letting Mockaco do its job.
