### ISSUE TITLE
Support for fake data file 

### ISSUE THREAD

**Issue by ofuenmayor** [natenho/Mockaco#51]
Indeed to paste a JSON on the mock file, can have a folder with all the responses and on the mock definition select the file to send a response. And if you want to use the same endpoint with a little change in the response only have to change the selected file.

**Comment by natenho** [comment]
Hello @ofuenmayor! It seems that Mockaco already supports your scenario, check this out:

Using the raw file response feature described in [Mocking binary/raw request/response](https://github.com/natenho/Mockaco/blob/master/doc/Mocking-RAW.md) you can select a raw response file based on the request:

Example:
```
{
  "request": {
    "method": "GET",
    "route": "/issue51/{selectedResponseFileName}"
  },
  "response": {
    "status": "OK",
    "headers": {
      "Content-Type": "application/xml"      
    },
    "file": "<#= "Mocks/issue51/" + Request.Route["selectedResponseFileName"]?.ToString() + ".json" #>"
  } 
}
```

Find attached a full working example ([issue51.zip](https://github.com/natenho/Mockaco/files/5066490/issue51.zip)) and let me know your thoughts. It basically switches among 3 different raw response files based on the requested path:

```console
F:\Code
λ curl localhost:5000/issue51/responseA
{

        "message": "This is the response A"
}
F:\Code
λ curl localhost:5000/issue51/responseB
{
        "message": "This is the response B"
}
F:\Code
λ curl localhost:5000/issue51/responseC
{
        "message": "This is the response C"
}
```

You can also bring more details on your own scenario so we can work on it.
Thank you for your suggestion! I hope it helps.

**Comment by ofuenmayor** [comment]
Hello @natenho thanks, I read the documentation but not understand can use the file that way. thanks so much for your time.
