### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by helderjmo** [natenho/Mockaco#52]
Im using Mockaco to mock an angular app and Im issuing some problems with CORS. It could be useful to add some cors support, using appsettings to setup allowed origins (for ex).

**Comment by natenho** [comment]
Hello @helderjmo, thanks for your suggestion. I was wondering if the best for mocking in this case would be to always allow any origin instead of implementing a fine-grained setting. Do you see any scenarios where this full CORS setup would be needed?

**Comment by helderjmo** [comment]
Hi @natenho! thank you for your feedback and sorry to be late in response. Unfortunely, I was not able to get a response from Mockaco from an angular app running localy. Always giving CORs error. So I just tryed to enhance your code giving cors support throught netcore middleware (configurable trough appsettings) and it works! If you want, I can propouse my solution here on github. Thank you.

**Comment by natenho** [comment]
Awesome, feel free to send pull requests whenever you find that your code could be useful for someone else. I also commited a simple solution a few days after you opened the issue, so you might want to merge yours here: https://github.com/natenho/Mockaco/tree/feature/52-cors-support
