### ISSUE TITLE
Publish as dotnet tool

### ISSUE THREAD

**Issue by fakhrulhilal** [natenho/Mockaco#56]
**Describe the solution you'd like**
Dotnet has its own ecosystem for publishing its executable binary. Dotnet tool is suitable choice because we can install and update the binary easily. 

**Describe alternatives you've considered**
The tool should be able to be installed as dotnet tool. Therefor, we don't care where the binary is located. When running the tool, we should be able to configure where required files/folder:
- Mocks
- Logs
- appSettings.json

This flexibility will allows us to run the tool with different mock configuration

**Comment by natenho** [comment]
Hi @fakhrulhilal, that sounds amazing! I'm going to do some research on how to implement it. Meanwhile I would appreciate if you could give some command line ideas that we could make available to facilitate the usage of the tool.

Thanks!

**Comment by fakhrulhilal** [comment]
Right, only webroot that comes in my mind. This param should be used for defining location for appSettings.json, Mocks & Logs folder. I think we can add more command later. Once published, it's easy to update the tool.

**Comment by natenho** [comment]
I see. I'm also thinking about the instance approach:

**A) Should the tool spawn a new Mockaco instance for each run? (using random ports or a port specified in command line)**
e.g.
```
# dotnet-mock c:\mocks-service-A
`[16:35:01 INF]  Now listening on: http://[::]:4654`
```
Another terminal:
```
# dotnet-mock c:\mocks-service-B
`[16:35:01 INF]  Now listening on: http://[::]:5465`
```

**B) Or should the tool configure a single Mockaco instance to use mocks from multiple folders:**

e.g.
```
# dotnet-mock c:\mocks-service-A
[16:35:01 INF]  Now listening on: http://[::]:80
[16:35:01 INF]  Added mocks from c:\mocks-service-A
```
Another terminal:
```
# dotnet-mock c:\mocks-service-B
[16:37:22 INF]  There is already an instance listening on: http://[::]:80
[16:37:22 INF]  Added mocks from c:\mocks-service-B
```

**Comment by fakhrulhilal** [comment]
Option A of course. That's why we tell the app root so it can find appSettings.json. Thus, he can find in which port it should listen to. If any existing port used, then it should fail. Conceptually, one run is separate instance. 
It's just like running web server (nginx/apache) multiple times. Like running multiple virtual sites (but not as this, it's too far). It's not apachectl, so we can control existing instance.

**Comment by natenho** [comment]
I agree with you, the other way would be more complex to implement by the
way.

Regarding the setting, I think there's no need to rely specifically on
appsettings.json, since one can also pass any setting through the command
line (out of the box):
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#command-line

**Comment by natenho** [comment]
I've just published the first public version of the dotnet tool! Check it out: https://www.nuget.org/packages/Mockaco/

```console
$ dotnet tool install --global mockaco
$ mockaco
```

These are the main available command line arguments:

--path Defines mocks path (if not passed, will use the current directory)
--urls Defines a specific address to listen (its the default .net web host parameter)
--logs Defines logs path e.g. C:\Logs\Mockaco.log (if not passed will use ".\Logs\Mockacko_.log")

There is some pending documentation, CI/versioning work, but the published version is already a good start!

Thank you for the suggestion!
