### ISSUE TITLE
Provide a simple api key auth to secure the whole Mockaco

### ISSUE THREAD

**Issue by alieniasty** [natenho/Mockaco#77]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Additional middleware could've been added, for example `AuthMiddleware` that would not be a part of the whole verification process. Why? Because If I would like to use Mockaco in a publicy available address I wouldn't want other people to actually access the Mockaco and peek what kind of requests I am sending. Sometimes there is a real user data in these requests.

**Describe alternatives you've considered**
There is a lot of alternatives like don't make Mockaco publicly available, obfuscate the data you are sending or simply don't send secure data to the mock server but this feature is simply nice to have.

**Additional context**
```
namespace Mockaco.Middlewares
{
    public class AuthMiddleware
    {
        private readonly RequestDelegate _next;

        public AuthMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            var apiKey = httpContext.Request.Headers["x-api-key"]
                .ToString();

            if (string.IsNullOrEmpty(apiKey) || !apiKey.Equals("some api key"))
            {
                httpContext.Response.StatusCode = StatusCodes.Status401Unauthorized;
                return;
            }

            await _next(httpContext);
        }
    }
}
```

**Comment by natenho** [comment]
@alieniasty Thanks for your suggestion! I wonder if that kind of "fake authentication" middleware should really be part of Mockaco. Since you're not doing a real authentication, why not to do it through the mock condition itself? Please check the example bellow:

```
{
	"request": {
		"route": "/",
		"condition": "<#= Request.Header["x-api-key"] == "MY-ULTRA-SECRET-KEY" #>"
	},
	"response": {
		"status": 200,
		"body": "Everything is fine!"
	}
}
```

So that way you're protecting your mock to return only when the given header is provided. There are other ways to that though, depending on the use case. What do you think?
