### ISSUE TITLE
High memory usage at startup

### ISSUE THREAD

**Issue by natenho** [natenho/Mockaco#82]
**Describe the bug**
When loading several mock template files with C# script, there is a huge increment in memory consumption during startup, that is freed as soon garbage collection is executed.

**To Reproduce**
Just load a reasonable number of mock files through mockaco. The amount of files containing scripts seems to be proportional to the consumed RAM.

**Expected behavior**
Should not consume so much RAM during startup.

**Screenshots**
![image](https://user-images.githubusercontent.com/4236481/145928566-fde48fb9-7626-46fc-bd29-f5d4e6cbe4d8.png)

**Comment by natenho** [comment]
This seems to be due to the CSharpScript engine startup. Mockaco compiles multiple delegates while loading mocks, and, although the scripts are properly cached, there is no control over the CSharpScript engine internals leading to these high memory allocations.

A workaround is to set Gatbage Collection aggressive (workstation mode), by setting an environment variable named `COMPlus_gcServer=0`

Example running docker:
`$ docker run -it --rm -p 5000:80 -e COMPlus_gcServer=0 -v /home/Mocks:/app/Mocks natenho/mockaco`

That actually does not solve the problem because in fact there are too many allocations being made by CSharpScript engine that I'm going to investigate further.

According [to this issue](https://github.com/dotnet/roslyn/issues/22219#issuecomment-351059798), moving the globalsType to another assembly may help.

There is also this issue refering to this topic: https://github.com/dotnet/roslyn/issues/16897#issuecomment-353356390

**Comment by natenho** [comment]
In a few tests, inspired by [this comment](https://github.com/dotnet/roslyn/issues/22219#issuecomment-452221583) I created a cached `MetadataResolver` which seems to dramatically reduce memory usage.

**Comment by gomete** [comment]
Hi @natenho,

We have added `GC.Collect()` to force the collect after running the `ScriptRunner` delegate [right after this `Invoke`](https://github.com/natenho/Mockaco/blob/0721dfc483cc7dac3a9c3423ab1760973815d84f/src/Mockaco/Templating/Scripting/ScriptRunnerFactory.cs#L30). It seems that it frees some memory that it is being allocated with the delegate and the memory stays stable sending more requests.

I have tested the `MetadataResolver` and it does not work in .NET 6 like they are describing. If it is modified to return an empty `InmutableArray` you need to provide all the used assemblies in the `ScriptOptions`.

```csharp
public override ImmutableArray<PortableExecutableReference> ResolveReference(string reference, string baseFilePath, MetadataReferenceProperties properties) => InmutableArray<PortableExecutableReference>.Empty.
```

**Comment by natenho** [comment]
@gomete Actually, I was trying to figure out doing a lot of experiments based on the links I mentioned before, moving code around and I came up with this [cached MetadataResolver] in the issue branch (https://github.com/natenho/Mockaco/blob/42b29d5596287b360fed8a16accd968e7dd5d281/src/Mockaco.Scripting/Scripting/ScriptRunnerFactory.cs).

I didn't test it too much since, but it seemed to be promising. I'll have to test it with .NET 6 aswell.
