### ISSUE TITLE
Request Template Matching: Read Request.Body["xxx"] within condition attribute.

### ISSUE THREAD

**Issue by senal** [natenho/Mockaco#83]
**Describe the bug**
I've added a condition which require to read some value from the request body.
`"condition":  "<#= Request.Body["LicenceNumber"].ToString() != "12345" #>",`
complete req/res mock json file
`{
  "request": {
    "method": "POST",
    "route": "dvs/driverLicence",
    "condition":  "<#= Request.Body["LicenceNumber"].ToString() != "12345" #>",

   },
  "response": {
      "body": {
      "id": "<#= Faker.Random.Guid() #>",
      "message": "This is not the ID",
    }

  }
}
`

However, when run the application (F5) on local. I get this null pointer exception

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ℛ*f08f062f-ae63-4554-bb9e-29ac7a1159ea#1-0
  StackTrace:
   at Submission#0.<<Initialize>>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Mockaco.TemplateTransformer.<Run>d__6.MoveNext() in C:\workspace\research\mocking_birds\MockServers\Mockaco\src\Mockaco\Templating\TemplateTransformer.cs:line 102

  This exception was originally thrown at this call stack:
    [External Code]
    Mockaco.TemplateTransformer.Run(string, Mockaco.IScriptContext) in TemplateTransformer.cs
`

**To Reproduce**
Please copy the above json file into the mock folder and use to route as defined in the route attribute.

**Expected behavior**
Application should initiate without any exceptions.
I can load the application with this error and it returns the expected behavior.
e.g if you provide the correct license number in the request body, it returns the expected response.

**Screenshots**
![image](https://user-images.githubusercontent.com/2841066/149871492-4164b8c7-ef49-4f6f-bd51-40ff9bdb1a29.png)

![image](https://user-images.githubusercontent.com/2841066/149871595-2e4d6073-c820-406e-86e0-173e5b93f039.png)

**Comment by natenho** [comment]
Hi, currently this behavior is by design, during the load there are evaluations over all scripts with objects having their default values set (null in this case). 

However, your mock should work as expected.

I agree that it seems odd at first sight and I'll keep this issue open to find a better solution ;).

To avoid the error, you can simply apply the [null conditional operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-) to your expression, like this:

```
{
  "request": {
    "method": "POST",
    "route": "dvs/driverLicence",
    "condition": "<#= Request.Body["LicenceNumber"].ToString() != "12345" #>"
  },
  "response": {
    "body": {
      "id": "<#= Faker.Random.Guid() #>",
      "message": "This is not the ID"
    }
  }
}
```

**Comment by senal** [comment]
@natenho, thanks for your prompt feedback.
I added the null conditional operator seems the exception disappeared but saw this error on the console log.

![image](https://user-images.githubusercontent.com/2841066/149875537-5c85593b-b522-496c-a2dd-9e4f44c7cd6e.png)

Any thoughts?

**Comment by natenho** [comment]
@senal there is a wrong leading "}" character at the end of your code:

![image](https://user-images.githubusercontent.com/4236481/149876644-62332f19-769b-4380-a2ca-bcf75cf7f9ad.png)

Notice that everything between <# and #> are pure C# code, and it should be able to be compiled!

**Comment by senal** [comment]
@natenho , good catch. I will close this ticket.
Thank you very much for your prompt support!
