### ISSUE TITLE
How to define multiple conditions or add the whole request body comparison as a condition

### ISSUE THREAD

**Issue by senal** [natenho/Mockaco#84]
**Is your feature request related to a problem? Please describe.**

I just need a way of conditionally filter a request base on the values provided in the request body.
following is an example of the request body
`{
    "BirthDate": "1986-09-15",
    "GivenName": "You",
    "MiddleName": "",
    "FamilyName": "Kim",
    "LicenceNumber": "12345",
    "StateOfIssue": "CMB",
    "ExpiryDate" : ""
}`

e.g 
conditions for each property.
`
"conditions": [
"<#= Request.Body["LicenceNumber"] == "12345" #>",
"<#= Request.Body["FamilyName"] == "Kim" #>",
"<#= Request.Body["GivenName"] == "You" #>",
]
`
One condition for the whole request body.
`
"condition": "<#= Request.Body.Equal(
{
"LicenceNumber": "12345"
"FamilyName": "Kim"
"GivenName": "You"
}
) #>",
`

**Describe the solution you'd like**
We need a way to apply conditions either by each property or comparing the whole request body in the condition attribute.

**Describe alternatives you've considered**
N/A

**Comment by natenho** [comment]
Notice that everything between <# and #> is C# code so you can use operators like && and || to achieve a comparison of multiple properties:

```
"condition":  "<#= Request.Body["LicenceNumber"] == "12345" && Request.Body["FamilyName"] == "Kim" && Request.Body["GivenName"] == "You" #>"
```

To compare the whole body is also possible, it's a JToken that you can serialize into JSON and compare.

**Comment by senal** [comment]
@natenho , Thank you very much for your detailed explanation.

P.S: Do you think we should update the document with this information?

**Comment by natenho** [comment]
@senal For sure! It would be fantastic if someone else could invest some time helping to improve Mockaco documentation! The C# scripting topic indeed lacks a lot of details of what can potentially be done. ;-)

**Comment by senal** [comment]
@natenho, great, I will see how can I add more content to the documentation.
I'm experimenting with Mockaco as a mock server. I can log all my findings and learning then eventually add them to the existing documentation to make it more comprehensive. Thanks for this imitative.
