### ISSUE TITLE
Error when build the docker image

### ISSUE THREAD

**Issue by senal** [natenho/Mockaco#85]
**Describe the bug**
First of all, Not sure  this is bug or something I'm doing wrong. Please see the below explanation.

I tried to build the image using `docker build ` command.
`docker build -t mockaco -f ./Docker/Dockerfile .`
and I get the following error:

![image](https://user-images.githubusercontent.com/2841066/150054650-452a8575-0816-4387-81d8-25b9d5d3af23.png)

please note that I ran this command within the `src/Mockaco` folder. 

**NOTE**
I did a slight change to the `COPY ./src/Mockaco/Mocks/hello.js /app/Mocks/` by removing `hello.json` file as I need to copy the whole directory to the `app/Mocks`

Please advice.

**Comment by natenho** [comment]
No problem! It's how docker works. You need to make sure you are in the root directory to execute the build command.

In your case, it seems that you are inside the `/src/Mockaco` directory, so you should execute: `docker build -t mockaco -f ./Docker/Dockerfile ../../`

**Comment by senal** [comment]
@natenho ,
Thank you as very much.
I got it working.

But I faced the below issue.
I have created 2 more mock files in the Mock directory (`dvsdriverlicencenok.json` and `dvsdriverlicenceok.json`). When I build the image and run it on my local, Mockaco always loads only the `hello.json` file. I doubt the other 2 files were copied to the Mock directory during the docker build.
Do you have any idea of this issue.
Below is a screen shot of the docker build result and the logs when I run the image on my local

![image](https://user-images.githubusercontent.com/2841066/150119646-4a1de79c-5f06-4c71-9b1e-0dba842bcb22.png)

Thanks

**Comment by natenho** [comment]
It's just a matter of adjusting the .dockerignore file removing the last lines.

Mocks are intentionally not copied into the base Mockaco container.

If you're not modifying the code, I recommend you to create a docker file and build your image using the official Mockaco docker image as your base image instead of rebuilding it from scratch like that.
