### ISSUE TITLE
Support for SSL w/Cert and Key would be nice!

### ISSUE THREAD

**Issue by norillsa** [natenho/Mockaco#86]
subject sez it all :)

**Comment by natenho** [comment]
@norillsa That support already exists. Mockaco leverages the native configurable .NET infrastructure and it uses Kestrel as the web server. Please refer to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0 on how to configure what you want :)
